#+STARTUP: hidestars
#+STARTUP: odd
#+STARTUP: showall

* Current tasks:
*** Finish sendMatrix which uses socket.socket.send(), so it needs to represent
    doubles/floats as bytes/char.

* TASKontrol
*** RTLSMclient
*** SoundClient
*** Solo-like graphical module
*** Dispatcher-like module

* Python style
*** TODO Do not compare with == (singleton), use 'is'
*** TODO Use .join() instead of +=
*** TODO Be explicit about which exception is catched
*** TODO endswith() instead of slicing string
*** TODO Use isinstance(obj, int) instead of comparing types
*** TODO Don't compare boolean values to True or False using ==

* Notes on developing in python:
*** Ipython:
***** Debugger:
******* Running 'run -d script' did not work:
	"AttributeError: Pdb instance has no attribute 'curframe'"
	https://bugs.launchpad.net/ubuntu/+source/ipython/+bug/381069
	But running "ipython -pdb" worked.
******* Trying to use pydb failed because it installed only for python2.4
******* SOLUTION: running 'ipython -pdb' worked fine.
***** TAB-autocompletion:
      It adds a blank space after the completion, very annoying.
      Try for example: cd /hom<TAB>
      http://mail.scipy.org/pipermail/ipython-user/2005-March/002612.html


* Links to tools:
*** Git:
    Crash course: http://git-scm.com/course/svn.html 
    For the lazy: http://www.spheredev.org/wiki/Git_for_the_lazy
    In emacs    : http://parijatmishra.wordpress.com/2008/09/06/up-and-running-with-emacs-and-git/
    In Ubuntu   : https://help.ubuntu.com/community/Git
*** Org-mode:
    http://orgmode.org/manual
